#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
测试JSON翻译器
"""

import os
import json
from json_translator import JsonTranslator


def test_json_translator():
    """Test the JSON translator"""
    
    print("测试JSON翻译器")
    print("=" * 40)
    
    # Look for JSON files generated by the DOCX converter
    json_files = []
    current_dir = os.getcwd()
    
    # Look for JSON files in current directory
    for file in os.listdir(current_dir):
        if file.endswith('.json') and 'fragments' in file.lower():
            json_files.append(file)
    
    # Also look for the test output files
    for file in os.listdir(current_dir):
        if file.startswith('test_output_') and file.endswith('.json'):
            json_files.append(file)
    
    if not json_files:
        print("未找到JSON文件")
        print("请先运行 docx_to_json.py 生成JSON文件")
        return
    
    print(f"找到 {len(json_files)} 个JSON文件:")
    for i, file in enumerate(json_files, 1):
        print(f"{i}. {file}")
    
    # Use the first JSON file for testing
    test_file = json_files[0]
    print(f"\n测试文件: {test_file}")
    
    # Check the content of the JSON file first
    try:
        with open(test_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        print(f"JSON文件包含 {len(data)} 个项目")
        
        # Show some sample items
        sample_items = list(data.items())[:5]
        print(f"\n前5个项目示例:")
        for i, (key, value) in enumerate(sample_items, 1):
            if len(value) > 50:
                value_display = value[:47] + "..."
            else:
                value_display = value
            print(f"{i}. '{key}' -> '{value_display}'")
        
        # Count items with Chinese
        chinese_count = 0
        english_count = 0
        
        for key, value in data.items():
            has_chinese = any('\u4e00' <= char <= '\u9fff' for char in value)
            if has_chinese:
                chinese_count += 1
            else:
                english_count += 1
        
        print(f"\n内容分析:")
        print(f"包含中文的项目: {chinese_count}")
        print(f"纯英文项目: {english_count}")
        
        if chinese_count == 0:
            print("没有需要翻译的中文内容")
            return
        
        # Ask user if they want to proceed with translation
        proceed = input(f"\n是否开始翻译？(y/n): ").strip().lower()
        if proceed not in ['y', 'yes', '是']:
            print("取消翻译")
            return
        
    except Exception as e:
        print(f"读取JSON文件时发生错误: {e}")
        return
    
    # Create translator and test
    try:
        print(f"\n开始翻译测试...")
        translator = JsonTranslator()
        
        output_file = f"translated_{test_file}"
        success = translator.translate_json_file(test_file, output_file)
        
        if success:
            print(f"\n✓ 翻译测试成功！")
            print(f"✓ 输出文件: {output_file}")
            
            # Verify the output
            if os.path.exists(output_file):
                with open(output_file, 'r', encoding='utf-8') as f:
                    translated_data = json.load(f)
                
                print(f"✓ 输出文件包含 {len(translated_data)} 个项目")
                
                # Check how many items still contain Chinese
                still_chinese = 0
                for key, value in translated_data.items():
                    if any('\u4e00' <= char <= '\u9fff' for char in value):
                        still_chinese += 1
                
                print(f"✓ 翻译完成后仍含中文的项目: {still_chinese}")
                print(f"✓ 成功翻译的项目: {len(translated_data) - still_chinese}")
                
        else:
            print(f"\n✗ 翻译测试失败")
            
    except Exception as e:
        print(f"测试过程中发生错误: {e}")
        import traceback
        traceback.print_exc()


def create_sample_json():
    """Create a sample JSON file for testing"""
    sample_data = {
        "Hello World": "Hello World",
        "测试文本": "测试文本", 
        "数字123保持不变": "数字123保持不变",
        "English text": "English text",
        "中英混合 English mixed": "中英混合 English mixed",
        "纯英文保持不变": "纯英文保持不变",
        "Another English text": "Another English text",
        "复杂的中文句子，包含标点符号！": "复杂的中文句子，包含标点符号！",
        "Mixed 混合文本 with numbers 123": "Mixed 混合文本 with numbers 123",
        "简单": "简单"
    }
    
    sample_file = "sample_for_translation.json"
    with open(sample_file, 'w', encoding='utf-8') as f:
        json.dump(sample_data, f, ensure_ascii=False, indent=2)
    
    print(f"创建了示例JSON文件: {sample_file}")
    return sample_file


def main():
    """Main function"""
    print("JSON翻译器测试工具")
    print("=" * 50)
    
    choice = input("选择操作:\n1. 测试现有JSON文件\n2. 创建示例JSON文件并测试\n请输入选择 (1/2): ").strip()
    
    if choice == "2":
        # Create sample and test
        sample_file = create_sample_json()
        
        translator = JsonTranslator()
        success = translator.translate_json_file(sample_file)
        
        if success:
            print("\n✓ 示例测试完成！")
        else:
            print("\n✗ 示例测试失败！")
    
    elif choice == "1":
        # Test existing files
        test_json_translator()
    
    else:
        print("无效选择")


if __name__ == "__main__":
    main() 